FROM ubuntu:22.04

LABEL description="Primary image for TeXing" \
    authors="Norbert Nemesh <ntnemesh@sberautotech.ru>"


# Container's user credential
ARG uid
ARG gid
ARG username
ARG home

ARG DEBIAN_FRONTEND=noninteractive \
ARG TERM=xterm

# Create the user
RUN groupadd --gid $gid $username && \
    useradd --uid $uid --gid $gid -m $username && \
    chown -R $uid:$gid /home/$username && \
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    apt-get update && \
    apt-get install -y sudo && \
    echo $username ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$username && \
    chmod 0440 /etc/sudoers.d/$username

# Update the system
RUN apt-get update && \
    apt-get install -y git && \
    apt-get install -y vim && \
    apt-get install -y bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR $home
